# development:
#   adapter: sqlite3
#   database: development.sqlite3
development:

  adapter: postgresql
  encoding: unicode
  database: pixtr_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: pixtr_test
  pool: 5
